language: node_js

node_js:
  - 8

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  ## now run cypress headlessly
  ## and record all of the tests.
  ## Cypress will search for a
  ## CYPRESS_PROJECT_ID and CYPRESS_RECORD_KEY environment variables
  - npm run test:record
  ## see recording of the test run at
  ## https://dashboard.cypress.io/#/projects/p7bh2z/runs
