export const events = {
    onAfterRenderNoAnchor: 'onAfterRenderNoAnchor',
    onClickOrTouch: 'onClickOrTouch',
    moveSlideLeft: 'moveSlideLeft',
    moveSlideRight: 'moveSlideRight',
    onInitialise: 'onInitialise',
    beforeInit: 'beforeInit',
    bindEvents: 'bindEvents',
    onDestroy: 'onDestroy',
    contentChanged: 'contentChanged',
    onScrollOverflowScrolled: 'onScrollOverflowScrolled',
    onScrollPageAndSlide: 'onScrollPageAndSlide',
    onKeyDown: 'onKeyDown',
    onMenuClick: 'onMenuClick',
    scrollPage: 'scrollPage',
    landscapeScroll: 'landscapeScroll',
    scrollBeyondFullpage: 'scrollBeyondFullpage',
    onPerformMovement: 'onPerformMovement',
    onSlideLeave: 'onSlideLeave',
    onLeave: 'onLeave',
    afterSectionLoads: 'afterSectionLoads',
    afterSlideLoads: 'afterSlideLoads',
};